volumes:
  wardrobify-data:
    external: true
services:
  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - wardrobify-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    ports:
      - 15432:5432

  front-end:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      HOST: "0.0.0.0"
      NODE_ENV: development

  back-end:
    build:
      context: ./back_end/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./back_end/api:/app
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres_db

  sneaks-api:
    build:
      context: ./sneaks/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./sneaks/api:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres_db
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 240
