# Generated by Django 4.0.3 on 2023-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_rest', '0002_account_profile_picture_account_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.URLField(default='https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg'),
        ),
    ]
