# Generated by Django 4.2.4 on 2023-12-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_picture",
            field=models.URLField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREPvmzUnSZWU_AQX3YpiUS5kpMldREZhYKMQ&usqp=CAU",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_level",
            field=models.CharField(
                choices=[("basic", "Basic"), ("premium", "Premium"), ("vip", "Vip")],
                default="basic",
                max_length=200,
            ),
        ),
    ]
