# Generated by Django 4.0.3 on 2023-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shoe",
            name="color",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shoe",
            name="price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="shoe",
            name="size",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="sku",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
