# Generated by Django 4.0.3 on 2023-10-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0002_shoe_category_shoe_color_shoe_price_shoe_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="brand",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
