# Generated by Django 4.0.3 on 2023-10-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0003_shoe_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="BinVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_href", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="shoe",
            name="bin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoes",
                to="shoes_rest.binvo",
            ),
        ),
    ]
