# Generated by Django 4.0.3 on 2023-10-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0004_binvo_shoe_bin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="binvo",
            name="name",
        ),
        migrations.AlterField(
            model_name="binvo",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
