# Generated by Django 4.0.3 on 2023-10-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0005_remove_binvo_name_alter_binvo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="bin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoes",
                to="shoes_rest.binvo",
            ),
        ),
    ]
