# Generated by Django 4.0.3 on 2023-10-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0006_alter_shoe_bin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binvo",
            name="id",
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="binvo",
            name="import_href",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="bin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoes",
                to="shoes_rest.binvo",
            ),
        ),
    ]
