# Generated by Django 4.0.3 on 2023-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0007_alter_binvo_id_alter_binvo_import_href_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binvo",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="binvo",
            name="import_href",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
