# Generated by Django 4.0.3 on 2023-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0008_alter_binvo_id_alter_binvo_import_href"),
    ]

    operations = [
        migrations.AddField(
            model_name="binvo",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
