# Generated by Django 4.0.3 on 2023-10-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0009_binvo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="gender",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shoe",
            name="picture_url",
            field=models.URLField(null=True),
        ),
    ]
