# Generated by Django 4.0.3 on 2023-10-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0010_shoe_gender_shoe_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="picture_url",
            field=models.URLField(max_length=400, null=True),
        ),
    ]
