# Generated by Django 4.0.3 on 2023-10-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes_rest", "0012_alter_shoe_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="description",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
