# Generated by Django 4.0.3 on 2023-10-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0016_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
