# Generated by Django 4.0.3 on 2023-10-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0018_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='shoe',
        ),
    ]
