# Generated by Django 4.0.3 on 2023-10-28 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0019_rename_product_rating_shoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='shoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_set', to='shoes_rest.shoe'),
        ),
    ]
