# Generated by Django 4.0.3 on 2023-10-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0021_accountvo_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='accountvo',
            name='is_staff',
        ),
    ]
