# Generated by Django 4.0.3 on 2023-10-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0022_remove_accountvo_is_active_remove_accountvo_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
    ]
