# Generated by Django 4.0.3 on 2023-10-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0023_rename_favorites_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvo',
            name='profile_picture',
            field=models.URLField(max_length=5000),
        ),
    ]
