# Generated by Django 4.0.3 on 2023-10-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0024_alter_accountvo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='accountvo',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
