# Generated by Django 4.0.3 on 2023-10-28 16:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0025_alter_accountvo_email_alter_accountvo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(choices=[(Decimal('1'), Decimal('1')), (Decimal('1.5'), Decimal('1.5')), (Decimal('2'), Decimal('2')), (Decimal('2.5'), Decimal('2.5')), (Decimal('3'), Decimal('3')), (Decimal('3.5'), Decimal('3.5')), (Decimal('4'), Decimal('4')), (Decimal('4.5'), Decimal('4.5')), (Decimal('5'), Decimal('5'))], decimal_places=1, max_digits=2, null=True),
        ),
    ]
