# Generated by Django 4.0.3 on 2023-10-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0026_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_account', to='shoes_rest.accountvo'),
        ),
    ]
