# Generated by Django 4.0.3 on 2023-11-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0027_rating_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='shoes_rest.accountvo'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('shoe', 'account')},
        ),
    ]
