# Generated by Django 4.0.3 on 2023-11-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0028_alter_favorite_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='sku',
        ),
        migrations.DeleteModel(
            name='BinVO',
        ),
    ]
