# Generated by Django 4.0.3 on 2023-11-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0029_remove_shoe_bin_remove_shoe_category_remove_shoe_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='gender',
        ),
    ]
